"""Runtime tool metadata; imports no executable tools."""

from agentloom.tools.catalog_types import ToolSpec, _spec


def tool_specs() -> tuple[ToolSpec, ...]:
    return (
        _spec(
            "shell_tool",
            "agentloom.adapters.smolagents.tools.shell.shell_tool",
            "core_shell",
            "Run a shell command with AgentLoom shell policy enforcement.",
            "shell",
            fixed_arg_names=("command", "timeout", "load_profile", "run_in_background"),
            is_read_only=False,
            is_concurrency_safe=False,
            max_result_chars=40000,
            output_kind="log",
            owner="runtime",
            provider="smolagents",
            capability="shell.execute",
            operation="shell",
            command_parameter="command",
        ),
        _spec(
            "check_background_task",
            "agentloom.adapters.smolagents.tools.shell.background_task_tools",
            "core_shell",
            "Read current output and status for a background shell task.",
            "shell",
            fixed_arg_names=("task_id",),
            is_read_only=True,
            max_result_chars=5000,
            output_kind="log",
            owner="runtime",
            provider="smolagents",
            capability="shell.status",
            operation="control",
        ),
        _spec(
            "kill_background_task",
            "agentloom.adapters.smolagents.tools.shell.background_task_tools",
            "core_shell",
            "Terminate a running background shell task.",
            "shell",
            fixed_arg_names=("task_id",),
            is_read_only=False,
            is_destructive=True,
            is_concurrency_safe=False,
            max_result_chars=3000,
            output_kind="log",
            owner="runtime",
            provider="smolagents",
            capability="shell.cancel",
            operation="control",
        ),
        _spec(
            "list_background_tasks",
            "agentloom.adapters.smolagents.tools.shell.background_task_tools",
            "core_shell",
            "List active and recent background shell tasks.",
            "shell",
            fixed_arg_names=(),
            is_read_only=True,
            max_result_chars=5000,
            output_kind="log",
            owner="runtime",
            provider="smolagents",
            capability="shell.list",
            operation="control",
        ),
        _spec(
            "read_file",
            "agentloom.adapters.smolagents.tools.file_ops.read_file",
            "core_file",
            "Read a file with pagination and read-state tracking.",
            "file_ops",
            fixed_arg_names=("file_path", "offset", "limit"),
            is_read_only=True,
            max_result_chars=None,
            path_params=("file_path",),
            output_kind="code",
            owner="runtime",
            provider="smolagents",
            capability="file.read",
            operation="read",
        ),
        _spec(
            "edit_file",
            "agentloom.adapters.smolagents.tools.file_ops.edit_file",
            "core_file",
            "Apply one or more unique text edits to an existing file.",
            "file_ops",
            fixed_arg_names=("file_path", "edits"),
            is_read_only=False,
            is_destructive=True,
            path_params=("file_path",),
            output_kind="text",
            owner="runtime",
            provider="smolagents",
            capability="file.edit",
            operation="write",
        ),
        _spec(
            "write_file",
            "agentloom.adapters.smolagents.tools.file_ops.write_file",
            "core_file",
            "Create or completely overwrite a file with read-state protection.",
            "file_ops",
            fixed_arg_names=("file_path", "content"),
            is_read_only=False,
            is_destructive=True,
            path_params=("file_path",),
            output_kind="text",
            owner="runtime",
            provider="smolagents",
            capability="file.write",
            operation="write",
        ),
        _spec(
            "list_directory",
            "agentloom.adapters.smolagents.tools.file_ops.directory_browser",
            "core_file",
            "List a directory tree with repository-oriented filtering.",
            "file_ops",
            fixed_arg_names=(
                "directory_path",
                "max_depth",
                "max_output_lines",
                "show_file_counts",
                "show_file_info",
                "include_hidden",
                "exclude_patterns",
                "count_timeout_seconds",
            ),
            is_read_only=True,
            max_result_chars=12000,
            path_params=("directory_path",),
            output_kind="text",
            owner="runtime",
            provider="smolagents",
            capability="file.list",
            operation="read",
        ),
        _spec(
            "grep_search",
            "agentloom.adapters.smolagents.tools.search.grep_tool",
            "core_search",
            "Search file contents using ripgrep-compatible regular expressions.",
            "search",
            fixed_arg_names=(
                "pattern",
                "path",
                "include",
                "output_mode",
                "case_insensitive",
                "context_lines",
                "before_context",
                "after_context",
                "multiline",
                "max_results",
                "offset",
            ),
            is_read_only=True,
            max_result_chars=20000,
            path_params=("path",),
            output_kind="search",
            owner="runtime",
            provider="smolagents",
            capability="search.grep",
            operation="read",
        ),
        _spec(
            "glob_search",
            "agentloom.adapters.smolagents.tools.search.glob_tool",
            "core_search",
            "Find files by glob pattern under a directory.",
            "search",
            fixed_arg_names=("pattern", "path", "max_results", "sort_by"),
            is_read_only=True,
            max_result_chars=10000,
            path_params=("path",),
            output_kind="search",
            owner="runtime",
            provider="smolagents",
            capability="search.glob",
            operation="read",
        ),
        _spec(
            "todo_write",
            "agentloom.tools.todo.todo_write",
            "planning",
            "Write the current task plan.",
            "planning",
            fixed_arg_names=("sanitize_inputs_outputs",),
            accepts_extra_fixed_args=True,
            is_read_only=False,
            is_destructive=False,
            is_concurrency_safe=False,
            max_result_chars=10000,
            output_kind="text",
            owner="runtime",
            provider="smolagents",
            capability="planning.todo",
            operation="control",
        ),
    )
