"""
ID generator module.

Uses the Snowflake algorithm to generate unique task IDs and agent IDs.
"""

import hashlib
from typing import Dict, Optional

from snowflake import SnowflakeGenerator


# Global Snowflake ID generator (default instance=1).
_snowflake_gen = SnowflakeGenerator(instance=1)

# Cache generators for different instances to avoid repeated creation.
_generator_cache: Dict[int, SnowflakeGenerator] = {}


def _get_generator(instance: int) -> SnowflakeGenerator:
    """Get or create a generator for the specified instance."""
    if instance not in _generator_cache:
        _generator_cache[instance] = SnowflakeGenerator(instance=instance)
    return _generator_cache[instance]


def generate_id(name: Optional[str] = None, prefix: str = "task") -> str:
    """Generate a unique ID using the Snowflake algorithm.

    Uses a name-derived instance for deterministic shard selection, ensuring
    IDs from the same name are generated by the same Snowflake instance.

    Args:
        name: Optional name used to compute the Snowflake instance (0-1023).
              When omitted, the default global instance is used.
        prefix: Prefix string prepended to the numeric ID, e.g. "task", "agent".

    Returns:
        str: ID in format "{prefix}_{snowflake_id}".

    Examples:
        >>> generate_id()
        'task_7234567890123456789'
        >>> generate_id("HaloOS project test")
        'task_7234567890123456790'
        >>> generate_id("search_agent", prefix="agent")
        'agent_7234567890123456791'
    """
    if name:
        hash_value = int(hashlib.md5(name.encode()).hexdigest(), 16)
        instance = hash_value % 1024
        gen = _get_generator(instance)
    else:
        gen = _snowflake_gen
    return f"{prefix}_{next(gen)}"
