"""Unified logging helpers for AgentLoom."""

from .agent_logger import EnhancedAgentLogger, AgentLoomLogLevel
from .logger_manager import (
    LazyLoggerAdapter,
    LoggerAdapter,
    LoggingConfigBuilder,
    LoggingConfigOverlay,
    NullLoggerBackend,
    UnifiedLogger,
    build_default_log_filename,
    build_run_timestamp_dirname,
    build_logger_backend_from_config,
    get_current_run_log_dir,
    get_global_logger,
    get_or_create_process_log_path,
    get_active_log_file_path,
    get_logger,
    initialize_logging,
    initialize_global_logger_once,
    merge_logging_config,
    resolve_log_file_path,
    resolve_logger,
    set_global_logger,
    validate_logging_config,
)

__all__ = [
    "AgentLoomLogLevel",
    "EnhancedAgentLogger",
    "UnifiedLogger",
    "LazyLoggerAdapter",
    "LoggerAdapter",
    "LoggingConfigBuilder",
    "LoggingConfigOverlay",
    "NullLoggerBackend",
    "initialize_logging",
    "initialize_global_logger_once",
    "get_logger",
    "resolve_logger",  # backward-compatible alias for get_logger
    "set_global_logger",
    "get_global_logger",
    "get_or_create_process_log_path",
    "build_default_log_filename",
    "build_run_timestamp_dirname",
    "build_logger_backend_from_config",
    "get_current_run_log_dir",
    "merge_logging_config",
    "validate_logging_config",
    "resolve_log_file_path",
    "get_active_log_file_path",
]
