"""
Application scaffold generator.

Generates a minimal demo script for a supervisor agent YAML configuration.

Usage (CLI)::

    loom create applications/<app>/workflows/<agent>.yaml
    loom create applications/<app>/workflows/<agent>.yaml -o my_app.py

Usage (Python API)::

    from src.scaffold import create_demo_script
    create_demo_script("applications/<app>/workflows/<agent>.yaml")
"""

from __future__ import annotations

import re
import textwrap
from pathlib import Path
from typing import Optional

import click

from src.lib.config import C
from src.workflows.workflow_manager import infer_category_from_yaml_path


_DEMO_TEMPLATE = textwrap.dedent('''\
    #!/usr/bin/env python3
    """
    {agent_name} – auto-generated application entry point.

    Generated by: python -m src create {yaml_rel_path}
    """

    import os
    import sys

    # Ensure project root is on sys.path.
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    if project_root not in sys.path:
        sys.path.insert(0, project_root)

    from src.runner import run_app


    def main():
        run_app("{yaml_rel_path}")


    if __name__ == "__main__":
        main()
''')


def _resolve_yaml_path(yaml_path: str | Path) -> Path:
    """Resolve *yaml_path* to an absolute path (same logic as runner)."""
    path = Path(yaml_path)
    if not path.is_absolute():
        path = Path(C.agent_root) / path
    path = path.resolve()
    if not path.exists():
        raise FileNotFoundError(f"YAML configuration file not found: {path}")
    return path


def _make_rel_path(absolute_path: Path) -> str:
    """Return the path relative to the project root as a POSIX string."""
    try:
        return str(absolute_path.relative_to(Path(C.agent_root).resolve()))
    except ValueError:
        return str(absolute_path)


def _sanitize_filename(name: str) -> str:
    """将 YAML name 转为安全的文件名片段。

    空格替换为下划线，移除特殊字符，只保留字母、数字和下划线。
    """
    name = name.strip().replace(" ", "_").replace("-", "_")
    name = re.sub(r"[^\w]", "", name)
    return name.lower() or "app"


def create_demo_script(
    yaml_path: str | Path,
    output_path: Optional[str | Path] = None,
    *,
    interactive: bool = False,
) -> Path:
    """Generate a minimal demo script for a supervisor YAML config.

    Args:
        yaml_path: Path to the supervisor YAML file.  Can be relative to
            the project root.
        output_path: Where to write the generated script.  When *None* it
            defaults to ``applications/{category}/{name}_app.py`` where
            *name* is taken from the YAML ``name`` field.
        interactive: If *True* and the target file already exists, prompt
            the user for confirmation before overwriting.  When *False*
            (the default for programmatic usage), raise
            :class:`FileExistsError` instead.

    Returns:
        The absolute :class:`Path` to the generated script.

    Raises:
        FileNotFoundError: If *yaml_path* does not exist.
        FileExistsError: If *output_path* already exists and the caller
            chose not to overwrite (either *interactive=False* or user
            declined the prompt).
    """
    resolved = _resolve_yaml_path(yaml_path)
    yaml_rel = _make_rel_path(resolved)
    category = infer_category_from_yaml_path(resolved)

    # Read YAML to get the agent name.
    import yaml as _yaml

    with resolved.open("r", encoding="utf-8") as fp:
        cfg = _yaml.safe_load(fp)
    agent_name = cfg.get("name", category) if isinstance(cfg, dict) else category
    safe_name = _sanitize_filename(agent_name)

    # Determine output location.
    if output_path is not None:
        out = Path(output_path)
        if not out.is_absolute():
            out = Path(C.agent_root) / out
    else:
        out = Path(C.agent_root) / "applications" / category / f"{safe_name}_app.py"

    out = out.resolve()

    # Handle existing file.
    if out.exists():
        if interactive:
            click.echo(f"\n⚠️  File already exists: {out}")
            if not click.confirm("Overwrite? (y/n)", default=False):
                raise FileExistsError(
                    f"Overwrite cancelled by user: {out}"
                )
        else:
            raise FileExistsError(
                f"Demo script already exists: {out}"
            )

    content = _DEMO_TEMPLATE.format(
        agent_name=agent_name,
        yaml_rel_path=yaml_rel,
    )

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    return out
