"""Shared default values for config/model layers."""

DEFAULT_MAX_TOKENS = 150000

DEFAULT_MODEL_TEMPERATURE = 0.1
DEFAULT_MODEL_TIMEOUT = 60
DEFAULT_MODEL_NUM_RETRIES = 5
DEFAULT_MODEL_RETRY_DELAY = 15.0
DEFAULT_MODEL_MAX_RETRY_DELAY = 100.0
DEFAULT_MODEL_CONTEXT_CACHE = False
DEFAULT_MODEL_REQUESTS_PER_MINUTE = 60
