"""Optional tool metadata; imports no executable tools."""

from agentloom.tools.catalog_types import ToolSpec, _spec


def tool_specs() -> tuple[ToolSpec, ...]:
    return (
        _spec(
            "write_markdown_file",
            "agentloom.tools.file_ops.markdown_writer",
            "markdown_report",
            "Write a Markdown report from structured sections.",
            "file_ops",
            fixed_arg_names=(
                "file_path",
                "sections",
                "title",
                "metadata",
                "overwrite",
                "create_directories",
                "encoding",
            ),
            is_read_only=False,
            is_destructive=True,
            path_params=("file_path",),
            output_kind="markdown",
            owner="optional",
            provider="agentloom",
            capability="write_markdown_file",
        ),
        _spec(
            "write_markdown_file_raw",
            "agentloom.tools.file_ops.markdown_writer",
            "markdown_report",
            "Write raw Markdown content to a file.",
            "file_ops",
            fixed_arg_names=(
                "file_path",
                "content_b64",
                "content_plain",
                "overwrite",
                "create_directories",
                "encoding",
            ),
            is_read_only=False,
            is_destructive=True,
            path_params=("file_path",),
            output_kind="markdown",
            owner="optional",
            provider="agentloom",
            capability="write_markdown_file_raw",
        ),
        _spec(
            "append_markdown_sections",
            "agentloom.tools.file_ops.markdown_writer",
            "markdown_report",
            "Append structured Markdown sections to an existing report.",
            "file_ops",
            fixed_arg_names=("file_path", "sections", "encoding"),
            is_read_only=False,
            is_destructive=True,
            path_params=("file_path",),
            output_kind="markdown",
            owner="optional",
            provider="agentloom",
            capability="append_markdown_sections",
        ),
        _spec(
            "get_file_outline",
            "agentloom.tools.file_ops.file_outliner",
            "code_nav",
            "Return a compact outline for a source file.",
            "code_nav",
            fixed_arg_names=(
                "file_path",
                "detail_level",
                "max_size_mb",
                "encoding",
                "include_line_numbers",
                "max_items_per_section",
            ),
            is_read_only=True,
            path_params=("file_path",),
            output_kind="code",
            owner="optional",
            provider="agentloom",
            capability="get_file_outline",
        ),
        _spec(
            "ast_grep_search_file",
            "agentloom.tools.search.ast_grep_tool",
            "code_nav",
            "Search source structure in one file using AST-aware matching.",
            "code_nav",
            fixed_arg_names=("file_path", "keyword", "language"),
            is_read_only=True,
            path_params=("file_path",),
            output_kind="search",
            owner="optional",
            provider="agentloom",
            capability="ast_grep_search_file",
        ),
        _spec(
            "lsp_find_definition",
            "agentloom.tools.search.lsp_tool",
            "code_nav",
            "Find a symbol definition using LSP or tree-sitter fallback.",
            "code_nav",
            fixed_arg_names=("file_path", "line", "character", "language"),
            is_read_only=True,
            path_params=("file_path",),
            output_kind="code",
            owner="optional",
            provider="agentloom",
            capability="lsp_find_definition",
        ),
        _spec(
            "lsp_find_references",
            "agentloom.tools.search.lsp_tool",
            "code_nav",
            "Find symbol references using LSP or tree-sitter fallback.",
            "code_nav",
            fixed_arg_names=("file_path", "line", "character", "language", "max_results"),
            is_read_only=True,
            path_params=("file_path",),
            output_kind="search",
            owner="optional",
            provider="agentloom",
            capability="lsp_find_references",
        ),
        _spec(
            "lsp_get_document_symbols",
            "agentloom.tools.search.lsp_tool",
            "code_nav",
            "List document symbols for one file.",
            "code_nav",
            fixed_arg_names=("file_path", "language"),
            is_read_only=True,
            path_params=("file_path",),
            output_kind="code",
            owner="optional",
            provider="agentloom",
            capability="lsp_get_document_symbols",
        ),
        _spec(
            "lsp_hover",
            "agentloom.tools.search.lsp_tool",
            "code_nav",
            "Return hover/type information at a source location.",
            "code_nav",
            fixed_arg_names=("file_path", "line", "character", "language"),
            is_read_only=True,
            path_params=("file_path",),
            output_kind="code",
            owner="optional",
            provider="agentloom",
            capability="lsp_hover",
        ),
        _spec(
            "lsp_get_workspace_symbols",
            "agentloom.tools.search.lsp_tool",
            "code_nav",
            "Search symbols in a workspace directory.",
            "code_nav",
            fixed_arg_names=("directory", "query", "language", "max_results"),
            is_read_only=True,
            path_params=("directory",),
            output_kind="search",
            owner="optional",
            provider="agentloom",
            capability="lsp_get_workspace_symbols",
        ),
    )
