"""Platform tool metadata; imports no executable tools."""

from agentloom.tools.catalog_types import ToolSpec, _spec


def tool_specs() -> tuple[ToolSpec, ...]:
    return (
        _spec(
            "loom_retrieve_context",
            "agentloom.tools.context.retrieve_context",
            "context",
            "Retrieve original content behind a ContextRef.",
            "context",
            fixed_arg_names=("ref", "query", "offset", "limit"),
            is_read_only=True,
            max_result_chars=None,
            output_kind="text",
            owner="platform",
            provider="agentloom",
            capability="loom_retrieve_context",
        ),
        _spec(
            "skill",
            "agentloom.tools.skills.skill_tool",
            "skills",
            "Load a specialized Skill when its description matches the current task.",
            "skills",
            fixed_arg_names=("name",),
            is_read_only=True,
            max_result_chars=20000,
            output_kind="text",
            owner="platform",
            provider="agentloom",
            capability="skill",
        ),
        _spec(
            "session_search",
            "agentloom.tools.self_learning.session_tools",
            "self_learning",
            "Search redacted records from prior AgentLoom runs.",
            "self_learning",
            fixed_arg_names=("query", "limit", "agent", "app", "since", "scope"),
            is_read_only=True,
            max_result_chars=30000,
            output_kind="text",
            owner="platform",
            provider="agentloom",
            capability="session_search",
        ),
        _spec(
            "session_scroll",
            "agentloom.tools.self_learning.session_tools",
            "self_learning",
            "Scroll around an indexed session event.",
            "self_learning",
            fixed_arg_names=("run_id", "event_id", "direction", "window"),
            is_read_only=True,
            max_result_chars=30000,
            output_kind="text",
            owner="platform",
            provider="agentloom",
            capability="session_scroll",
        ),
        _spec(
            "memory",
            "agentloom.tools.self_learning.memory_tool",
            "self_learning",
            "Read or change curated project/current-application facts that remain useful after this run.",
            "self_learning",
            fixed_arg_names=(
                "action",
                "scope",
                "kind",
                "memory_key",
                "text",
                "trigger",
                "symptom",
                "learned_action",
                "verification",
            ),
            is_read_only=False,
            is_concurrency_safe=False,
            max_result_chars=20000,
            output_kind="text",
            owner="platform",
            provider="agentloom",
            capability="memory",
        ),
        _spec(
            "skill_manage",
            "agentloom.tools.self_learning.skill_manage_tool",
            "self_learning",
            "Create and update generated skill proposal packages.",
            "self_learning",
            fixed_arg_names=(
                "action",
                "name",
                "content",
                "old_string",
                "new_string",
                "path",
                "target",
            ),
            is_read_only=False,
            is_concurrency_safe=False,
            max_result_chars=20000,
            output_kind="text",
            owner="platform",
            provider="agentloom",
            capability="skill_manage",
        ),
    )
